services:
  db:
    image: postgres:15
    container_name: carniceria_db
    environment:
      POSTGRES_USER: el_negro_admin
      POSTGRES_PASSWORD: el_negro_2026
      POSTGRES_DB: carniceria
    ports:
      - "5432:5432"
    volumes:
      - carniceria_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  carniceria_pgdata:
